### ISSUE TITLE
Animal rescue website

### ISSUE THREAD

**Issue by sophielangman** [sophielangman/animal-rescue-website#1]
@charlie-quinn

Hello! I'm quite aware that this is not meeting all of markbots requirements, I just figured I'd submit the work I have and get any marks I can from it. Have a great break!

This is the original site : http://www.freedomdogrescue.ca/

**Comment by charlie-quinn** [comment]
✅ `This portion of your final assignment has been graded. A marking rubric has been sent to your college email address.`

⚠️`Reminder: please close this issue once it has been resolved.`
